package com.jun.plugin.common.log.dao;

import com.jun.plugin.common.dataaccess.BaseRepository;
import com.jun.plugin.common.log.entity.SysLog;


/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T15:14:20+08:00
 *
 */

public interface SysLogDAO extends BaseRepository<SysLog, Long> {

}
