package com.jun.plugin.boot.core.service;

import java.util.List;

import com.jun.plugin.boot.core.entity.Permission;
import com.jun.plugin.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */
 
public interface PermissionService extends BaseService<Permission, Long>{
 	
	public List<Permission> getAllMenus();
	
	public List<Permission> getOperations(Long parentId);
	
	public void addBaseOperations(Long parentId, String pClassName,String moduleCode);
	
	
}
