package com.jun.plugin.boot.core.service;

import org.springframework.stereotype.Service;

import com.jun.plugin.boot.core.entity.Role;
import com.jun.plugin.common.dataaccess.BaseServiceImpl;

/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */

@Service
public class RoleServiceImpl extends BaseServiceImpl<Role, Long> implements RoleService {

}
