package com.jun.plugin.boot.core.service;

import com.jun.plugin.boot.core.entity.Role;
import com.jun.plugin.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */
 
public interface RoleService extends BaseService<Role, Long>{
	
}
