package com.jun.plugin.boot.core.service;

import java.util.List;

import com.jun.plugin.boot.core.entity.UserRole;
import com.jun.plugin.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2018-10-23T14:08:29+08:00
 *
 */
 
public interface UserRoleService extends BaseService<UserRole, Long>{

	public List<Long> findRoleIdsByUserId(Long userId);
	
	public void deleteInBatchByUserId(Long userId);

	public void updateUserRoles(Long userId, List<Long> roleIds);
	
}
