package com.jun.plugin.boot.web.controller;

import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.jun.plugin.boot.core.service.UserRoleService;
import com.jun.plugin.boot.web.model.UserRoleRequestRequest;
import com.jun.plugin.common.log.LogModuleCode;
import com.jun.plugin.common.log.Logger;
import com.jun.plugin.common.model.JsonData;

/**
 *
 * 
 * Generated by fieldmeta at 2018-10-23T14:08:29+08:00
 *
 */

@Controller("adminUserRoleController")
@RequestMapping("/admin/action/boot/userrole")
public class UserRoleController {
	@Autowired
	UserRoleService userRoleService;

	
	@ResponseBody
	@RequestMapping("/findRoleIdsByUserId")
	@RequiresPermissions("boot:userRole:query")
	public JsonData findRoleIdsByUserId(@RequestParam Long userId) {
		return JsonData.success(userRoleService.findRoleIdsByUserId(userId));
	}

	@Logger(name = "更新用户角色" , moduleCode = LogModuleCode.BOOT)
	@ResponseBody
	@RequestMapping("/updateUserRoles")
	@RequiresPermissions("boot:userRole:update")
	public JsonData updateUserRoles(@RequestBody UserRoleRequestRequest userRoleRequest) {

		userRoleService.updateUserRoles(userRoleRequest.getUserId(), userRoleRequest.getRoleIds());
		return JsonData.success();
	}

}
