package com.jun.plugin.common.log.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jun.plugin.common.dataaccess.BaseServiceImpl;
import com.jun.plugin.common.log.dao.LoginLogDAO;
import com.jun.plugin.common.log.entity.LoginLog;



/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T22:34:30+08:00
 *
 */
 
@Service
public class LoginLogServiceImpl  extends BaseServiceImpl<LoginLog, Long> implements LoginLogService{
	@Autowired
	LoginLogDAO loginLogDAO;
}
