package com.jun.plugin.boot.core.dao;

import com.jun.plugin.boot.core.entity.Permission;
import com.jun.plugin.common.dataaccess.BaseRepository;


/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */

public interface PermissionDAO extends BaseRepository<Permission, Long> {
	
}
