package com.jun.plugin.boot.core.dao;

import java.util.List;

import org.springframework.data.repository.query.Param;

import com.jun.plugin.boot.core.entity.RolePermission;
import com.jun.plugin.common.dataaccess.BaseRepository;
import com.slyak.spring.jpa.TemplateQuery;


/**
 *
 * 
 * Generated by fieldmeta at 2018-10-23T14:08:29+08:00
 *
 */

public interface RolePermissionDAO extends BaseRepository<RolePermission, Long> {

	@TemplateQuery
	public List<Long> findPermissionIdsByRoleId(@Param("roleId") Long roleId);
	
}
