package com.jun.plugin.common.log.service;

import com.jun.plugin.common.dataaccess.BaseService;
import com.jun.plugin.common.log.entity.SysLog;



/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T15:14:20+08:00
 *
 */
 
public interface SysLogService extends BaseService<SysLog, Long>{

}
