package com.jun.plugin.common.log.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jun.plugin.common.dataaccess.BaseServiceImpl;
import com.jun.plugin.common.log.dao.SysLogDAO;
import com.jun.plugin.common.log.entity.SysLog;



/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T15:14:20+08:00
 *
 */
 
@Service
public class SysLogServiceImpl  extends BaseServiceImpl<SysLog, Long> implements SysLogService{
	@Autowired
	SysLogDAO sysLogDAO;
}
